language: ruby

script: bundle exec rake spec

rvm:
  - 2.0.0
  - 2.1
  - 2.2.3
  - ruby-head
gemfile:
  - gemfiles/Gemfile-rails.3.2.x
  - gemfiles/Gemfile-rails.4.0.x
  - gemfiles/Gemfile-rails.4.1.x
  - gemfiles/Gemfile-rails.4.2.x

sudo: false

matrix:
  exclude:
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails.3.2.x
  allow_failures:
    - rvm: ruby-head
