name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        ruby_version: [ruby-head, '3.1', '3.0', '2.7']
        gemfile:
          - gemfiles/Gemfile-rails.edge
          - gemfiles/Gemfile-rails.7.0.x
          - gemfiles/Gemfile-rails.6.1.x
        api: ['0', '1']

        include:
          - ruby_version: '2.7'
            gemfile: gemfiles/Gemfile-rails.6.0.x
          - ruby_version: '2.7'
            gemfile: gemfiles/Gemfile-rails.6.0.x
            api: '1'

          - ruby_version: '2.6'
            gemfile: gemfiles/Gemfile-rails.6.1.x
          - ruby_version: '2.6'
            gemfile: gemfiles/Gemfile-rails.6.1.x
            api: '1'
          - ruby_version: '2.6'
            gemfile: gemfiles/Gemfile-rails.6.0.x
          - ruby_version: '2.6'
            gemfile: gemfiles/Gemfile-rails.6.0.x
            api: '1'
          - ruby_version: '2.6'
            gemfile: gemfiles/Gemfile-rails.5.2.x
          - ruby_version: '2.6'
            gemfile: gemfiles/Gemfile-rails.5.2.x
            api: '1'
          - ruby_version: '2.6'
            gemfile: gemfiles/Gemfile-rails.5.1.x
          - ruby_version: '2.6'
            gemfile: gemfiles/Gemfile-rails.5.1.x
            api: '1'
          - ruby_version: '2.6'
            gemfile: gemfiles/Gemfile-rails.5.0.x
          - ruby_version: '2.6'
            gemfile: gemfiles/Gemfile-rails.5.0.x
            api: '1'

          - ruby_version: '2.5'
            gemfile: gemfiles/Gemfile-rails.5.2.x

          - ruby_version: '2.4'
            gemfile: gemfiles/Gemfile-rails.5.2.x

          - ruby_version: '2.3'
            gemfile: gemfiles/Gemfile-rails.5.2.x
          - ruby_version: '2.3'
            gemfile: gemfiles/Gemfile-rails.4.2.x
            bundler_version: '1'

          - ruby_version: '2.2'
            gemfile: gemfiles/Gemfile-rails.5.2.x

          - ruby_version: '2.1'
            gemfile: gemfiles/Gemfile-rails.4.2.x
            bundler_version: '1'

    runs-on: ubuntu-18.04
    env:
      API: ${{ matrix.api }}
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler: ${{ matrix.bundler_version }}
          bundler-cache: true
        continue-on-error: ${{ matrix.allow_failures == 'true' }}
      - run: bundle exec rake
        continue-on-error: ${{ matrix.allow_failures == 'true' }}
